CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    car_model VARCHAR(150),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(9, 6) NOT NULL,
    CONSTRAINT ck_cities_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_cities_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL REFERENCES users (id),
    departure_city_id BIGINT NOT NULL REFERENCES cities (id),
    arrival_city_id BIGINT NOT NULL REFERENCES cities (id),
    meeting_point VARCHAR(500) NOT NULL,
    departure_at TIMESTAMPTZ NOT NULL,
    seats_total INTEGER NOT NULL,
    seats_available INTEGER NOT NULL,
    price_per_seat NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trips_seats_total CHECK (seats_total BETWEEN 1 AND 8),
    CONSTRAINT ck_trips_seats_available CHECK (seats_available BETWEEN 0 AND seats_total),
    CONSTRAINT ck_trips_price CHECK (price_per_seat > 0),
    CONSTRAINT ck_trips_cities CHECK (departure_city_id <> arrival_city_id),
    CONSTRAINT ck_trips_status CHECK (status IN ('OPEN', 'FULL', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips (id),
    passenger_id BIGINT NOT NULL REFERENCES users (id),
    seats INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT ck_bookings_seats CHECK (seats BETWEEN 1 AND 8),
    CONSTRAINT ck_bookings_status CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

-- Cancelled bookings stay in history; only active bookings must be unique.
CREATE UNIQUE INDEX uq_bookings_confirmed_passenger_trip
    ON bookings (trip_id, passenger_id) WHERE status = 'CONFIRMED';

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips (id),
    sender_id BIGINT NOT NULL REFERENCES users (id),
    content TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips (id),
    rater_id BIGINT NOT NULL REFERENCES users (id),
    rated_id BIGINT NOT NULL REFERENCES users (id),
    score INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ratings_score CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT ck_ratings_different_users CHECK (rater_id <> rated_id),
    CONSTRAINT uq_ratings_trip_rater_rated UNIQUE (trip_id, rater_id, rated_id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users (id),
    target_type VARCHAR(20) NOT NULL,
    -- The target table depends on target_type; existence is checked by the service.
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reports_target_type CHECK (target_type IN ('TRIP', 'USER', 'MESSAGE')),
    CONSTRAINT ck_reports_status CHECK (status IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX idx_trips_search ON trips (departure_city_id, arrival_city_id, departure_at)
    WHERE status = 'OPEN';
CREATE INDEX idx_trips_driver ON trips (driver_id);
CREATE INDEX idx_bookings_passenger ON bookings (passenger_id);
CREATE INDEX idx_bookings_trip ON bookings (trip_id);
CREATE INDEX idx_messages_trip_sent ON messages (trip_id, sent_at, id);
CREATE INDEX idx_ratings_rated ON ratings (rated_id);
CREATE INDEX idx_reports_status ON reports (status);
